language: node_js
node_js:
  - 14 # uses version 14
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
  - npm install -g firebase-tools
script:
  #- npm test # test the code
  - npm run build-client # make the bundle
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
#  before_deploy:
#    - rm -rf node_modules # omit from the tarball, since we skip cleanup
#  deploy:
#    skip_cleanup: true # prevents travis from deleting the build
#    provider: firebase
#    message: "Deployed via Travis to Firebase"
#    token:
#      secure: YOUR-***ENCRYPTED***-API-KEY-HERE # see README
